### ISSUE TITLE
Possible to add IOS?

### ISSUE THREAD

**Issue by sachismo** [keijiro/jp.keijiro.rtmidi#13]
Hello. Great work on the addition of apple silicon support! Works Flawlessly.

I noticed the latest release of RtMidi now supports IOS..

Wondering if you think it is possible on the roadmap to add that to this library?

Thanks for all you do!

**Comment by keijiro** [comment]
Unfortunately, I can't simply migrate RtMidi to the new version because it abandoned C support. Now it requires C++.

C# doesn't support direct interoperability with C++. It means that I have to implement a C wrapper. It requires a significant amount of time.

I wonder if I should look for another library as a backend rather than investing more time on RtMidi.

**Comment by sachismo** [comment]
Ahh. I did not realize that until now. You must have worked from the c fork before? Yeah that does seem to make it complicated to have to wrap it twice. 

It seems like there is a lot between drywetmidi and managed-midi libraries done on the native c# side. But still seems like a lot to juggle.. I can’t believe unity is still not implementing anything natively for this.

let me know if there’s anything I can do to help further the process!
